config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :hotels do
    resources :orders
  end
  resources :hotels do
    member do
      put "like", to: "hotels#upvote"
      put "unlike", to: "hotels#downvote"
    end
  end
  root "hotels#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hotel.rb
class Hotel < ActiveRecord::Base
    acts_as_votable
    has_many :orders
    belongs_to :user
    searchable do
      text :name
    end

    validates :name, :presence => true
    validates :location, :presence => true
    validates :about, :presence => true
end

app/models/order.rb
class Order < ActiveRecord::Base
    belongs_to :hotel
    belongs_to :user

    validates :name, :presence => true
    validates :number, :presence => true
    validates :location, :presence => true
    validates :order, :presence => true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :hotels
  has_many :orders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  before_action :find_hotel, only: [:show, :upvote, :downvote]
  def index
    @search = Hotel.search do
      fulltext params[:search]
    end
    @hotels = @search.results
    render :index
  end

  def show
      @hotel = Hotel.find(params[:id])
      render :show
  end

  def new
    @hotel = current_user.hotels.build
    render :new
  end

  def create
    @hotel = current_user.hotels.build(hotel_params)
    if @hotel.save
      redirect_to  hotels_path
    else
      render :new
    end
  end
  def upvote
    @hotel.upvote_by current_user
    redirect_to :back
  end
  def downvote
    @hotel.downvote_by current_user
    redirect_to :back
  end
private
  def hotel_params
    params.require(:hotel).permit(:name, :location, :about)
  end
  def find_hotel
    @hotel = Hotel.find(params[:id])
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
    def new
      @hotel = Hotel.find(params[:hotel_id])
      @order = @hotel.orders.new
    end
    def create
      @hotel = Hotel.find(params[:hotel_id])
      @order = @hotel.orders.new(order_params)
      if @order.save
        redirect_to hotel_path(@order.hotel)
      else
        render :new
      end
    end

  private
    def order_params
      params.require(:order).permit(:name, :order, :location, :number)
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/hotels/index.html.erb
<% if user_signed_in?%>
<div class="search row">
  <div class="col-md-4">
    <%= link_to "Register hotel", new_hotel_path, class: "btn btn-primary"%>
  </div>
  <div class="col-md-8">
    <%= form_tag hotels_path, :method => :get do%>
    <p>
      <%= text_field_tag :search, params[:search], class: "search1", placeholder: "Search Hotel"%>
      <%= submit_tag :Search, :name => nil, class: "btn btn-primary"%>
    </p>
    <% end %>
  </div>

</div>
<div class="container row">
  <div class="hotels col-md-8">
    <h2 class="text-center head34">Hotels/Restaurants/Joints</h2>
    <ul>
      <% @hotels.each do |hotel|%>
        <p class="thumbnail text-center hots"><%= link_to hotel.name, hotel_path(hotel), class: "gstyle"%><br>
        <%= hotel.location%></p>
      <%end%>

    </ul>
  </div>
    <%end%>
    <%if !user_signed_in?%>
      <div class="message col-md-8">
        <p>Sign Up or Login to enjoy our services</p>
      </div>
    <%end%>
  <div class="tweets col-md-4">
    <h2 class="text-center head34">Tweets</h2>
    <ul>
      <% TwitterApi.our_public_tweets.each do |tweet|%>
        <p><%= tweet.text%></p>
      <%end%>
    </ul>
  </div>
</div>

app/views/hotels/new.html.erb
<div class="col-md-6">
  <%= form_for @hotel do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %><br>

      <%= f.label :location %>
      <%= f.text_field :location %><br>

      <%= f.label :about %>
      <%= f.text_area :about %><br>

      <%= f.submit  %>
    <% end %>

</div>

app/views/hotels/show.html.erb
<h2 class="show-h2 text-center"><%= @hotel.name%></h2>
<h3 class="show-h3 text-center"><%= @hotel.location%></h3>
<h3 class="show-h3 text-center"><%= @hotel.about%></h3>
<div class="like">
  <%= link_to like_hotel_path(@hotel), method: :put, class: "btn btn-primary" do%>
    <span>Like</span>
    <span class="badge"><%=@hotel.get_upvotes.size%></span>
  <%end%> &nbsp
  <%= link_to unlike_hotel_path(@hotel), method: :put, class: "btn btn-primary" do%>
    <span>Dislike</span>
    <span class="badge"><%=@hotel.get_downvotes.size%></span>
  <%end%>
</div>

<p class="order2"><%= link_to "Place an order", new_hotel_order_path(@hotel), class: "btn btn-primary" %></p>
<ul>
  <%if @hotel.user == current_user%>
  <table class="table table-striped table-hover">
    <tr>
      <th>Customer</th>
      <th>Pieces</th>
      <th>Order</th>
      <th>Location</th>
    </tr>
    <% @hotel.orders.each do |order|%>
    <tr id="order">
      <td><%= order.name%></td>
      <td><%= order.number%></td>
      <td><%= order.order%></td>
      <td><%= order.location%></td>
    </tr>
    <% end%>
  </table>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hotel Delivery</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="/stylesheets/bootstrap.css" media="screen" title="no title">
    <link rel="stylesheet" href="/stylesheets/styles.css" media="screen" title="no title">
    <link href="https://fonts.googleapis.com/css?family=Audiowide" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Jura" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Marcellus+SC" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Cinzel+Decorative" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Philosopher" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Calligraffitti" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Petit+Formal+Script" rel="stylesheet">
  </head>

  <body>
    <nav class="navbar navbar-fixed-top navbar-default">
       <div class="container-fluid">
         <div class="navbar-header">
           <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
             <span class="sr-only">Toggle navigation</span>
             <span class="icon-bar"></span>
             <span class="icon-bar"></span>
             <span class="icon-bar"></span>
           </button>
           <a class="navbar-brand icon gstyle1" href="/">Home</a>
         </div>
         <div id="navbar" class="navbar-collapse collapse">
           <ul class="nav navbar-nav navbar-right right-navs">
             <%if !user_signed_in?%>

             <%= link_to "SignUp", new_user_registration_path%> ||
             <%= link_to "LogIn", new_user_session_path%>
             <%end%>
             <%if user_signed_in?%>
             <%= link_to "logout", destroy_user_session_path, :method => :delete%>
             <%end%> <br>
           </ul>
         </div>
       </div>
     </nav>
    <div class="splash">
      <p class="head-text"><span class="head-text-2">Food</span> <span class="head-text-3">Delivery</span></p>
      <p class="head-text-1"><span class="head-text-4">(Order from your</span> <span class="head-text-5">favourite restaurant/hotel/joint)</span></p>
    </div>

    <%= yield %>

    <script type="text/javascript" src="/javascripts/bootstrap.min.js"></script>
    <script type="text/javascript" src="/javascripts/jquery.js"></script>
  </body>
</html>

app/views/orders/new.html.erb
<div class="col-md-6">
  <%= form_for [@hotel, @order] do |f|%>
     <%= f.label :Name %>
     <%= f.text_field :name %><br>

     <%= f.label :Pieces %>
     <%= f.text_field :number %><br>

     <%= f.label :Food %>
     <%= f.text_field :order %><br>

     <%= f.label :Location %>
     <%= f.text_field :location %><br>

     <p><%= f.submit %></p>
   <% end %>
</div>